// src/constants/groupConstants.ts

export const DEFAULT_VEHICLE_GROUPS = [
  'STND MONOSOF 7 SEAT AUTO',
  'MEDIUM 4X4 MANUAL', 
  'SHORT WHEEL BASE VAN MAN',
  'MID - SIZE CROSSOVER AUTO',
  'SMALL HATCHBACK AUTO',
  'MEDIUM 4X4 AUTO',
  'MEDIUM 4X4 PREMIUM AUTO',
  'CITY CAR AUTO',
  'MEDIUM WHEEL BASE VAN',
  'MPV AUTO 8 SEAT PREMIUM',
  'DOUBLE CAB PICK UP',
  'LONG WHEEL BASE ELECTRIC',
  'COMPACT/WAC MAN 7 SEAT',
  'LONG WHEEL BASE VAN',
  'MPV AUTO 9 SEAT',
  'MPV MANUAL 17 MANUAL',
  'LOW LOADER - LLD',
  'ESTATE AUTO',
  'SMALL VAN',
  'CREW CAB 5 SEAT MAN',
  'MID - SIZE CROSSOVER MAN',
  'SINGLE CAB TIPPER',
  'LUTON BOX VAN TAIL LIFT',
  'LWB REFRIGERTED VAN',
  'SWB REFRIGERTED VAN',
  'EX LONG WHEEL BASE',
  'SHORT WHEEL BASE VAN AUTO',
  'MPV MANUAL 14 SEAT',
  'MPV MANUAL 11 SEAT',
  'MPV AUTO 8 SEAT',
  'STND MONOSOF 7 SEAT AUTO',
  'STND MONOSOF 7 SEAT MAN',
  'CREW CAB 5 SEAT AUTO',
  'CREW CAB 5 SEAT AUTO',
  'STANDARD 4X4 AUTO',
  'COMPACT CROSSOVER AUTO',
  'COMPACT CROSSOVER MANUAL',
  'SMALL HATCHBACK PREMIUM AUTO',
  'SMALL HATCHBACK MAN',
  'CITY CAR MANUAL',
  'EXECUTIVE LARGE 4X4 - EXCL4'
] as const;

export const GROUP_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' }
] as const;

export const PRICING_VALIDATION = {
  MIN_RATE: 0,
  MAX_RATE: 999999,
  DECIMAL_PLACES: 2
} as const;